# Generated by Django 2.2.14 on 2020-07-06 09:04

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование категории')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ')),
                ('root_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bid.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование матрицы')),
            ],
            options={
                'verbose_name': 'Матрица товаров',
                'verbose_name_plural': 'Матрицы товаров',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование организации')),
                ('UNP', models.CharField(max_length=10, verbose_name='УНП')),
                ('branch_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код филиала')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование склада')),
                ('stock_type', models.CharField(choices=[('O', 'Обычный'), ('C', 'Склад-холодильник'), ('F', 'Склад-морозильник')], default='O', max_length=1, verbose_name='Формат объекта')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Полное наименование меры исчисления')),
                ('short_name', models.CharField(max_length=10, verbose_name='Краткое наименование меры исчисления')),
                ('type', models.CharField(choices=[('W', 'Весовой'), ('P', 'Штучный')], default='P', max_length=1, verbose_name='Тип единицы измерения')),
            ],
            options={
                'verbose_name': 'Мера исчисления',
                'verbose_name_plural': 'Меры исчисления',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование организации')),
                ('UNP', models.CharField(max_length=10, verbose_name='УНП')),
                ('branch_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код филиала')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('product_matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bid.ProductMatrix', verbose_name='Матрица товаров')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bid.Stock', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Торговый объект',
                'verbose_name_plural': 'Торговые объекты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=13, unique=True, verbose_name='Штрих-код')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='ЧПУ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('storage_condition', models.CharField(choices=[('O', 'Обычное'), ('C', 'Охлаждённое'), ('F', 'Замороженное')], default='O', max_length=1, verbose_name='Состояние хранения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bid.Category', verbose_name='Категория')),
                ('matrix', models.ManyToManyField(to='bid.ProductMatrix', verbose_name='Матрица товаров')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bid.Unit', verbose_name='Мера исчисления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['barcode', 'name'], name='bid_product_barcode_d4e845_gin'),
        ),
    ]
